### ISSUE TITLE
Line missing

### ISSUE THREAD

**Issue by Ironclad17** [rekaXua/demosaic_project#12]
I receive this error:
"Traceback (most recent call last):
  File "E:\demosaic_project\demosaic_project_ESRGAN.py", line 28, in <module>
    import architecture as arch
ModuleNotFoundError: No module named 'architecture'"

Is there a line missing that indicates the location of architecture.py?

**Comment by Ironclad17** [comment]
Also if I try to run architecture.py I get:
"Traceback (most recent call last):
  File "E:\demosaic_project\architecture.py", line 4, in <module>
    import block as B
ModuleNotFoundError: No module named 'block'"
